export const GET_OPERATIONS_API = "GET/OPERATIONS/API";
export const GET_ID_OPERATIONS_API = "GET/ID/OPERATIONS/API";
// export const POST_OPERATIONS_API = "POST/OPERATIONS/API";
// export const PUT_OPERATIONS_API = "PUT/OPERATIONS/API";
// export const DELETE_OPERATIONS_API = "DELETE/OPERATIONS/API";
export const GET_LATEST_OPERATIONS_API = "GET/LATEST/OPERATIONS/API";

export const SET_LOADING = 'SET/LOADING';