export const GET_OPERATIONS_API = "GET/COUNTRIES/API";
// export const POST_OPERATIONS_API = "POST/COUNTRIES/API";
// export const PUT_OPERATIONS_API = "PUT/COUNTRIES/API";
// export const DELETE_OPERATIONS_API = "DELETE/COUNTRIES/API";

export const SET_LOADING = 'SET/LOADING';